version: '3.8'
services:
  backend:
    build: ./mts-test-backend
    ports:
      - "1337:1337"
    volumes:
      - ./mts-test-backend/data/uploads:/app/data/uploads
      - strapi_database:/app/data
      - strapi_config:/app/config
    env_file:
      - ./mts-test-backend/.env
    environment:
      - NODE_ENV=production
  frontend:
    build: ./mts-test-frontend
    ports:
      - "80:80"
    depends_on:
      - backend 

volumes:
  strapi_database:
  strapi_config: 